set_device -family {PolarFire} -die {MPF300T_ES}
read_verilog -mode system_verilog -lib COREAHBTOAPB3_LIB {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\Actel\DirectCore\COREAHBTOAPB3\3.1.100\rtl\vlog\core\coreahbtoapb3_ahbtoapbsm.v}
read_verilog -mode system_verilog -lib COREAHBTOAPB3_LIB {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\Actel\DirectCore\COREAHBTOAPB3\3.1.100\rtl\vlog\core\coreahbtoapb3_apbaddrdata.v}
read_verilog -mode system_verilog -lib COREAHBTOAPB3_LIB {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\Actel\DirectCore\COREAHBTOAPB3\3.1.100\rtl\vlog\core\coreahbtoapb3_penablescheduler.v}
read_verilog -mode system_verilog -lib COREAHBTOAPB3_LIB {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\Actel\DirectCore\COREAHBTOAPB3\3.1.100\rtl\vlog\core\coreahbtoapb3.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\COREAHBTOAPB3_0\COREAHBTOAPB3_0.v}
read_verilog -mode system_verilog -lib COREAHBLITE_LIB {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\Actel\DirectCore\CoreAHBLite\5.4.102\rtl\vlog\core\coreahblite_slavearbiter.v}
read_verilog -mode system_verilog -lib COREAHBLITE_LIB {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\Actel\DirectCore\CoreAHBLite\5.4.102\rtl\vlog\core\coreahblite_slavestage.v}
read_verilog -mode system_verilog -lib COREAHBLITE_LIB {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\Actel\DirectCore\CoreAHBLite\5.4.102\rtl\vlog\core\coreahblite_defaultslavesm.v}
read_verilog -mode system_verilog -lib COREAHBLITE_LIB {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\Actel\DirectCore\CoreAHBLite\5.4.102\rtl\vlog\core\coreahblite_addrdec.v}
read_verilog -mode system_verilog -lib COREAHBLITE_LIB {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\Actel\DirectCore\CoreAHBLite\5.4.102\rtl\vlog\core\coreahblite_masterstage.v}
read_verilog -mode system_verilog -lib COREAHBLITE_LIB {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\Actel\DirectCore\CoreAHBLite\5.4.102\rtl\vlog\core\coreahblite_matrix4x16.v}
read_verilog -mode system_verilog -lib COREAHBLITE_LIB {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\CoreAHBL_0\CoreAHBL_0_0\rtl\vlog\core\coreahblite.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\CoreAHBL_0\CoreAHBL_0.v}
read_verilog -mode system_verilog -lib COREAPB3_LIB {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\Actel\DirectCore\CoreAPB3\4.1.100\rtl\vlog\core\coreapb3_muxptob3.v}
read_verilog -mode system_verilog -lib COREAPB3_LIB {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\Actel\DirectCore\CoreAPB3\4.1.100\rtl\vlog\core\coreapb3_iaddr_reg.v}
read_verilog -mode system_verilog -lib COREAPB3_LIB {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\Actel\DirectCore\CoreAPB3\4.1.100\rtl\vlog\core\coreapb3.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\CoreAPB3_0\CoreAPB3_0.v}
read_verilog -mode system_verilog -lib COREAXITOAHBL_LIB {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\Actel\DirectCore\COREAXITOAHBL\3.5.100\rtl\vlog\core\CoreAXItoAHBL_AXIOutReg.v}
read_verilog -mode system_verilog -lib COREAXITOAHBL_LIB {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\Actel\DirectCore\COREAXITOAHBL\3.5.100\rtl\vlog\core\CoreAXItoAHBL_WSTRBAddrOffset.v}
read_verilog -mode system_verilog -lib COREAXITOAHBL_LIB {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\Actel\DirectCore\COREAXITOAHBL\3.5.100\rtl\vlog\core\CoreAXItoAHBL_WSTRBPopCntr.v}
read_verilog -mode system_verilog -lib COREAXITOAHBL_LIB {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\Actel\DirectCore\COREAXITOAHBL\3.5.100\rtl\vlog\core\CoreAXItoAHBL_readByteCnt.v}
read_verilog -mode system_verilog -lib COREAXITOAHBL_LIB {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\Actel\DirectCore\COREAXITOAHBL\3.5.100\rtl\vlog\core\CoreAXItoAHBL_AXISlaveCtrl.v}
read_verilog -mode system_verilog -lib COREAXITOAHBL_LIB {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\Actel\DirectCore\COREAXITOAHBL\3.5.100\rtl\vlog\core\CoreAXItoAHBL_RAM_syncWrAsyncRd.v}
read_verilog -mode system_verilog -lib COREAXITOAHBL_LIB {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\Actel\DirectCore\COREAXITOAHBL\3.5.100\rtl\vlog\core\CoreAXItoAHBL_synchronizer.v}
read_verilog -mode system_verilog -lib COREAXITOAHBL_LIB {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\Actel\DirectCore\COREAXITOAHBL\3.5.100\rtl\vlog\core\CoreAXItoAHBL_AHBMasterCtrl.v}
read_verilog -mode system_verilog -lib COREAXITOAHBL_LIB {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\CoreAXITOAHBL_0\CoreAXITOAHBL_0_0\rtl\vlog\core\CoreAXItoAHBL.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\CoreAXITOAHBL_0\CoreAXITOAHBL_0.v}
read_verilog -mode system_verilog -lib COREAXITOAHBL_LIB {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\CoreAXITOAHBL_1\CoreAXITOAHBL_1_0\rtl\vlog\core\CoreAXItoAHBL.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\CoreAXITOAHBL_1\CoreAXITOAHBL_1.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\CoreGPIO_IN\CoreGPIO_IN_0\rtl\vlog\core\coregpio.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\CoreGPIO_IN\CoreGPIO_IN.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\CoreGPIO_OUT\CoreGPIO_OUT_0\rtl\vlog\core\coregpio.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\CoreGPIO_OUT\CoreGPIO_OUT.v}
read_verilog -mode system_verilog -lib COREJTAGDEBUG_LIB {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\Actel\DirectCore\COREJTAGDEBUG\3.1.100\core\corejtagdebug_ujtag_wrapper.v}
read_verilog -mode system_verilog -lib COREJTAGDEBUG_LIB {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\Actel\DirectCore\COREJTAGDEBUG\3.1.100\core\corejtagdebug_bufd.v}
read_verilog -mode system_verilog -lib COREJTAGDEBUG_LIB {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\Actel\DirectCore\COREJTAGDEBUG\3.1.100\core\corejtagdebug_uj_jtag.v}
read_verilog -mode system_verilog -lib COREJTAGDEBUG_LIB {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\Actel\DirectCore\COREJTAGDEBUG\3.1.100\core\corejtagdebug.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\CoreJTAGDebug_0\CoreJTAGDebug_0.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\CoreRESET_PF_0\CoreRESET_PF_0_0\core\corereset_pf.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\CoreRESET_PF_0\CoreRESET_PF_0.v}
read_verilog -mode system_verilog -lib CORETIMER_LIB {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\Actel\DirectCore\CoreTimer\2.0.103\rtl\vlog\core\coretimer.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\CoreTimer_0\CoreTimer_0.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\CoreTimer_1\CoreTimer_1.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\CoreUARTapb_0\CoreUARTapb_0_0\rtl\vlog\core_obfuscated\Clock_gen.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\CoreUARTapb_0\CoreUARTapb_0_0\rtl\vlog\core_obfuscated\Rx_async.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\CoreUARTapb_0\CoreUARTapb_0_0\rtl\vlog\core_obfuscated\Tx_async.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\CoreUARTapb_0\CoreUARTapb_0_0\rtl\vlog\core_obfuscated\fifo_256x8_g5.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\CoreUARTapb_0\CoreUARTapb_0_0\rtl\vlog\core_obfuscated\CoreUART.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\CoreUARTapb_0\CoreUARTapb_0_0\rtl\vlog\core_obfuscated\CoreUARTapb.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\CoreUARTapb_0\CoreUARTapb_0.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_gluebridge.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_queue_28.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_queue_29.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_queue_30.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_queue_32.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_axi4buffer_buffer.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_queue_33.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_axi4buffer.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_queue_48.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_axi4deinterleaver.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_axi4id_indexer_trim.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_axi4id_indexer.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_queue_18.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_queue_22.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_axi4user_yanker_yank.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_axi4user_yanker.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_coreplex_local_interrupter_clint.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_capture_chain.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_capture_update_chain_1.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_capture_update_chain.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_jtag_bypass_chain.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_capture_update_chain_2.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_async_reset_reg.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_async_reset_reg_vec_w4_i15.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_jtag_state_machine.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_negative_edge_latch_2.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_negative_edge_latch.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_jtag_tap_controller.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_debug_transport_module_jtag.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_async_reset_reg_vec_w1_i0.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_async_reset_reg_vec_w2_i0.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_int_sync_crossing_source_2.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_int_xbar.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_synchronizer_shift_reg_w31_d3.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_int_xing.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tlbuffer_memory_bus_master_tlbuffer.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tlxbar_memory_bus.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_memory_bus_mem_buses_0.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tlatomic_automata_periphery_bus_slave_tlfragmenter.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tlbuffer_periphery_bus_slave_tlbuffer.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_queue_1.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_queue.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tlbuffer_periphery_bus_slave_tlfragmenter.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_repeater_1.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_repeater_3.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tlfragmenter_periphery_bus_slave_tlfragmenter.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tlxbar_periphery_bus.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_periphery_bus_pbus.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_async_reset_synchronizer_shift_reg_w1_d3_i0.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_reset_catch_and_sync_d3.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_amoalu.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_arbiter_1.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_arbiter.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_data_arrays_0_ext.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_data_arrays_0.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_dcache_data_array.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tag_array_ext.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tag_array.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tlb.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_dcache_dcache.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_data_arrays_0_0_ext.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_data_arrays_0_0.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tag_array_0_ext.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tag_array_0.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_icache_icache.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_shift_queue.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tlb_1.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_frontend_frontend.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_hella_cache_arbiter.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_int_sync_crossing_sink_1.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_synchronizer_shift_reg_w1_d3.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_int_sync_crossing_sink.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_int_xbar_int_xbar.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_alu.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_breakpoint_unit.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_csrfile.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_rvcexpander.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_ibuf.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_mul_div.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_plusarg_reader.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_rocket.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_queue_11.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_queue_13.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_queue_14.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_queue_15.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_queue_6.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tlbuffer_system_bus.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tlxbar_tl_master_xbar.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_rocket_tile_tile.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tlcache_cork_system_bus.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tlfifofixer_system_bus.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_simple_lazy_module_system_bus_from_tiletile.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_queue_2.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_queue_3.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_queue_4.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tlbuffer_system_bus_slave_tlbuffer.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tlfifofixer_system_bus_pbus_tlfifofixer.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tlsplitter_system_bus_master_tlsplitter.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_repeater.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tlwidth_widget_system_bus_slave_tlwidth_widget.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_identity_module.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tlxbar_system_bus.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_system_bus_sbus.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_async_reset_synchronizer_shift_reg_w1_d4_i0.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_async_valid_sync_3.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_async_reset_synchronizer_shift_reg_w1_d1_i0.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_async_valid_sync_4.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_async_valid_sync_5.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_synchronizer_shift_reg_w12_d1.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_async_queue_sink_2.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_synchronizer_shift_reg_w54_d1.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_async_queue_sink_1.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_async_valid_sync_1.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_async_valid_sync_2.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_async_valid_sync.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_async_queue_source_2.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tlasync_crossing_sink_dmi_xing.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tldebug_module_inner_dm_inner.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tldebug_module_inner_async_dm_inner.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_async_queue_source_1.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_dmito_tl_dmi2tl.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_int_sync_crossing_source.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_synchronizer_shift_reg_w42_d1.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_async_queue_sink.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_async_queue_source.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tlasync_crossing_source_dm_inner.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_async_reset_reg_vec_w32_i0.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tldebug_module_outer_dm_outer.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tlxbar_dmi_xbar.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tldebug_module_outer_async_dm_outer.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tldebug_module_debug.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_queue_55.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_queue_56.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tlerror_error.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tlfilter.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_level_gateway.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_queue_10.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tlplic_plic.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_queue_16.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_queue_17.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tlto_axi4_converter.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_queue_54.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tlto_axi4.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_repeater_4.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_tlwidth_widget.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi_rocket_system.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0_0\core\miv_rv32ima_l1_axi.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\MiV_RV32IMA_L1_AXI_0\MiV_RV32IMA_L1_AXI_0.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\PF_CCC_0\PF_CCC_0_0\PF_CCC_0_PF_CCC_0_0_PF_CCC.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\PF_CCC_0\PF_CCC_0.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\PF_INIT_MONITOR_0\PF_INIT_MONITOR_0_0\PF_INIT_MONITOR_0_PF_INIT_MONITOR_0_0_PF_INIT_MONITOR.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\PF_INIT_MONITOR_0\PF_INIT_MONITOR_0.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\PF_OSC_0\PF_OSC_0_0\PF_OSC_0_PF_OSC_0_0_PF_OSC.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\PF_OSC_0\PF_OSC_0.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\PF_SRAM_0\PF_TPSRAM_AHB_AXI_0\PF_SRAM_0_PF_TPSRAM_AHB_AXI_0_PF_TPSRAM.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\PF_SRAM_0\COREAHBLSRAM_PF_0\rtl\vlog\core\CoreAHBLSRAM_AHBLSramIf.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\PF_SRAM_0\COREAHBLSRAM_PF_0\rtl\vlog\core\CoreAHBLSRAM_SramCtrlIf.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\PF_SRAM_0\COREAHBLSRAM_PF_0\rtl\vlog\core\CoreAHBLSRAM_PF.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\PF_SRAM_0\PF_SRAM_0.v}
read_verilog -mode system_verilog {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\BaseDesign\BaseDesign.v}
set_top_level {BaseDesign}
read_sdc -component {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\component\work\PF_CCC_0\PF_CCC_0_0\PF_CCC_0_PF_CCC_0_0_PF_CCC.sdc}
derive_constraints
write_sdc {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\constraint\BaseDesign_derived_constraints.sdc}
write_pdc {C:\GitHub-LSRAM-12.3\Future-Avalanche-Board\Libero_Projects\MiV_AXI_PF_Avalanche_ES\constraint\fp\BaseDesign_derived_constraints.pdc}
